server:
  port: 8888

logging:
  level:
    web: debug
spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: localhost
    port: 6379

oauth:
  github:
    clientId: aa551416af28b71b6aed
    secret: f2ad88a7e7cc8855acfea0ab35657dccd28c0154
    redirect: http://localhost:8888
  google:
    client-id: 460276430486-10is0l0i6qq1vn6mjjnqnrsfqjg673ss.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8888/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
    scope: profile

auth:
  url: "http://localhost:9001/"
third:
  url: "http://localhost:9000/"

# https://accounts.google.com/o/oauth2/auth?client_id=460276430486-10is0l0i6qq1vn6mjjnqnrsfqjg673ss.apps.googleusercontent.com460276430486-10is0l0i6qq1vn6mjjnqnrsfqjg673ss.apps.googleusercontent.com&redirect_uri=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&response_type=code&scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
# https://darrenlog.tistory.com/40?category=945132
# https://ksh-coding.tistory.com/66#%F0%9F%8E%AF%20OAuthAttributes%20%EC%A0%84%EC%B2%B4%20%EC%BD%94%EB%93%9C-1
