server:
  port: 8889

logging:
  level:
    web: info

spring:
  application:
    name: studyProject-FrontServer
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: localhost
    port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

auth:
  authentication:
    url: http://localhost:8000/authentication
  authorization:
    url: http://localhost:8000/authorization
api:
  member:
    url: http://localhost:8000/members

# https://accounts.google.com/o/oauth2/auth?client_id=460276430486-10is0l0i6qq1vn6mjjnqnrsfqjg673ss.apps.googleusercontent.com460276430486-10is0l0i6qq1vn6mjjnqnrsfqjg673ss.apps.googleusercontent.com&redirect_uri=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&response_type=code&scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
# https://darrenlog.tistory.com/40?category=945132
# https://ksh-coding.tistory.com/66#%F0%9F%8E%AF%20OAuthAttributes%20%EC%A0%84%EC%B2%B4%20%EC%BD%94%EB%93%9C-1
