server:
  port: 8888

spring:
  auth:
    url: "http://localhost:9001/"
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: localhost
    port: 6379